version: "3"
services:
  multitenancy:
    image: multitenancy-jpa-postgresql
    build:
      context: .
    depends_on:
    - postgres
    ports:
    - "8081:8080"
  postgres:
    image: postgres
    environment:
    - POSTGRES_DB=multitenancy
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
    - "5433:5432"
